// <auto-generated />
namespace UnverstityAccountingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class HisobModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HisobModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202105010814038_HisobModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
